In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import gensim.models as gsm
import gensim.downloader
import pandas as pd
import time
import string
import nltk
nltk.download('punkt')
import numpy as np
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec
import matplotlib.pyplot as plt

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


## Load Data - Full Data

### Raw Data

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/full_data/emoji_nsp_dataset_train.csv')
df_val = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/full_data/emoji_nsp_dataset_valid.csv')
df_test = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/full_data/emoji_nsp_dataset_test.csv')

In [ ]:
df_train.head()

index  ... follows?
0  50553  ...        1
1  74541  ...        0
2  50992  ...        1
3  95343  ...        0
4  60555  ...        0

[5 rows x 4 columns]

In [ ]:
df_train.count()

index             15540
tweets            15540
emoji_sentence    15540
follows?          15540
dtype: int64

### Load Tokens

In [ ]:
with open('/content/drive/MyDrive/2021_NLU/data/full_data/full_data.pkl', 'rb') as f:  
    x_train_tokenized, x_train_normal, x_val_tokenized, x_val_normal, x_test_tokenized, x_test_normal, empty_indices_train, x_train_tokenized_2, \
                 x_train_normal_2, empty_indices_val, x_val_tokenized_2, x_val_normal_2, y_train, y_val, y_train_2, y_val_2, y_test, y_test_2,\
                 empty_indices_test, x_test_normal_2, x_test_tokenized_2 = pickle.load(f)

In [ ]:
df_test['tokenized_tweets'] = x_test_tokenized
df_test['tokenized_len'] = df_test['tokenized_tweets'].apply(lambda x: len(x))
print(df_test['tokenized_len'].mean())
print(df_test['tokenized_len'].median())

14.242000901306895
10.0


### Load Vectors

In [ ]:
#AVERAGE VECTORS
with open('/content/drive/MyDrive/2021_NLU/data/full_data/full_vec.pkl', 'rb') as f:  
    X_train_vec, X_val_vec, X_test_vec = pickle.load(f)

In [ ]:
#CONCATENATED VECTORS
with open('/content/drive/MyDrive/2021_NLU/data/full_data/full_vec.pkl', 'rb') as f:  
    X_train_vec_concat, X_val_vec_concat, X_test_vec_concat = pickle.load(f)

## Load Data - (ONLY) SINGLE EMOJI 

### Raw Data

In [ ]:
df_sing_train = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/single_emoji/emoji_nsp_dataset_single_emoji_train.csv')
df_sing_val = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/single_emoji/emoji_nsp_dataset_single_emoji_valid.csv')
df_sing_test = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/single_emoji/emoji_nsp_dataset_single_emoji_test.csv')

### Load Tokens

In [ ]:
with open('/content/drive/MyDrive/2021_NLU/data/single_emoji/single_emoji.pkl', 'rb') as f:  
    x_train_sing_tokenized, x_train_sing_normal, x_val_sing_tokenized, x_val_sing_normal, x_test_sing_tokenized, x_test_sing_normal, empty_indices_sing_train, x_train_sing_tokenized_2, \
                 x_train_sing_normal_2, empty_indices_sing_val, x_val_sing_tokenized_2, x_val_sing_normal_2, y_sing_train, y_sing_val, y_train_sing_2, y_val_sing_2, y_sing_test, y_test_sing_2,\
                 empty_indices_sing_test, x_test_sing_normal_2, x_test_sing_tokenized_2 = pickle.load(f)

In [ ]:
len(x_train_sing_tokenized_2)

15015

### Load Vectors

In [ ]:
# AVERAGE VECETORS
with open('/content/drive/MyDrive/2021_NLU/data/single_emoji/single_emoji_vec.pkl', 'rb') as f:  
    X_train_sing_vec, X_val_sing_vec, X_test_sing_vec = pickle.load(f)

In [ ]:
# CONCATENATED VECTORS
with open('/content/drive/MyDrive/2021_NLU/data/single_emoji/single_emoji_vec_concat.pkl', 'rb') as f:  
    X_train_sing_vec_concat, X_val_sing_vec_concat, X_test_sing_vec_concat = pickle.load(f)

## Load Data - (ONLY) MULTI EMOJIS WITH REPEATS 

### Raw Data

In [ ]:
df_mul_repeat_train = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/multi_emoji/emoji_nsp_dataset_multi_emoji_train.csv')
df_mul_repeat_val = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/multi_emoji/emoji_nsp_dataset_multi_emoji_valid.csv')
df_mul_repeat_test = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/multi_emoji/emoji_nsp_dataset_multi_emoji_test.csv')

In [ ]:
df_mul_repeat_train.head()

index  ... follows?
0   6704  ...        1
1  10651  ...        1
2   6345  ...        1
3   5268  ...        1
4   5897  ...        1

[5 rows x 4 columns]

### Load Tokens

In [ ]:
with open('/content/drive/MyDrive/2021_NLU/data/multi_emoji/mul_repeat_emojis.pkl', 'rb') as f:  
    x_train_mul_repeat_tokenized, x_train_mul_repeat_normal, x_val_mul_repeat_tokenized, x_val_mul_repeat_normal, x_test_mul_repeat_tokenized, x_test_mul_repeat_normal, empty_indices_mul_repeat_train, x_train_mul_repeat_tokenized_2, \
                 x_train_mul_repeat_normal_2, empty_indices_mul_repeat_val, x_val_mul_repeat_tokenized_2, x_val_mul_repeat_normal_2, y_mul_repeat_train, y_mul_repeat_val, y_train_mul_repeat_2, y_val_mul_repeat_2, y_mul_repeat_test, y_test_mul_repeat_2,\
                 empty_indices_mul_repeat_test, x_test_mul_repeat_normal_2, x_test_mul_repeat_tokenized_2 = pickle.load(f)

### Load Vectors

In [ ]:
# AVERAGE VECTORS
with open('/content/drive/MyDrive/2021_NLU/data/multi_emoji/mul_repeat_emojis_vec.pkl', 'rb') as f:  
    X_train_mul_repeat_vec, X_val_mul_repeat_vec, X_test_mul_repeat_vec = pickle.load(f)

In [ ]:
# CONCATENATED VECTORS
with open('/content/drive/MyDrive/2021_NLU/data/multi_emoji/mul_repeat_emojis_vec.pkl', 'rb') as f:  
    X_train_mul_repeat_vec_concat, X_val_mul_repeat_vec_concat, X_test_mul_repeat_vec_concat = pickle.load(f)

## Load Data FULL DATA (SINGLE AND MULTI) WITH NO REPEATS 

### Raw Data

In [ ]:
df_mul_train = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/no_repeats/emoji_nsp_dataset_no_repeats_train.csv')
df_mul_val = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/no_repeats/emoji_nsp_dataset_no_repeats_valid.csv')
df_mul_test = pd.read_csv('/content/drive/MyDrive/2021_NLU/data/no_repeats/emoji_nsp_dataset_no_repeats_test.csv')

In [ ]:
df_mul_train.head()

index  ... follows?
0  50553  ...        1
1  74541  ...        0
2  50992  ...        1
3  95343  ...        0
4  60555  ...        0

[5 rows x 4 columns]

### Load Tokens

In [ ]:
with open('/content/drive/MyDrive/2021_NLU/data/no_repeats/mul_emojis.pkl', 'rb') as f:  
    x_train_mul_tokenized, x_train_mul_normal, x_val_mul_tokenized, x_val_mul_normal, x_test_mul_tokenized, x_test_mul_normal, empty_indices_mul_train, x_train_mul_tokenized_2, \
                 x_train_mul_normal_2, empty_indices_mul_val, x_val_mul_tokenized_2, x_val_mul_normal_2, y_mul_train, y_mul_val, y_train_mul_2, y_val_mul_2, y_mul_test, y_test_mul_2,\
                 empty_indices_mul_test, x_test_mul_normal_2, x_test_mul_tokenized_2 = pickle.load(f)

### Load Vectors

In [ ]:
# AVERAGE VECTORS
with open('/content/drive/MyDrive/2021_NLU/data/no_repeats/mul_emojis_vec.pkl', 'rb') as f:  
    X_train_mul_vec, X_val_mul_vec, X_test_mul_vec = pickle.load(f)

In [ ]:
# CONCATENATED VECTORS
with open('/content/drive/MyDrive/2021_NLU/data/no_repeats/mul_emojis_vec.pkl', 'rb') as f:  
    X_train_mul_vec_concat, X_val_mul_vec_concat, X_test_mul_vec_concat = pickle.load(f)

## LogisticRegression Model

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix
from sklearn.metrics import make_scorer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

def metric(y_true, y_pred):
    return f1_score(y_true, y_pred, average='weighted')

my_scorer = make_scorer(metric, greater_is_better=True)

In [ ]:
def run_model(model, X_train, y_train, X_val, y_val):
  print('     ## Fitting')
  model.fit(X_train, y_train)
  print('     ## Predicting')
  preds = model.predict(X_val)
  print(' ## F1 Score (weighted) is -', f1_score(y_val, preds, average='weighted'))
  print(' ## Accuracy is -', accuracy_score(y_val, preds))
  print('      ')
  print('               Confusion Matrix')
  print(confusion_matrix(y_val, preds))

In [ ]:
lr = LogisticRegression()

In [ ]:
def run_model_gridsearch_lr(model, X_train, y_train, X_val, y_val):
  
  cv=5
  parameters = {'C': np.logspace(0, 4, 10),'penalty': ['l1', 'l2']}
  clf = GridSearchCV(model, parameters, cv=cv, n_jobs=-1, scoring=my_scorer, verbose=0)
  print(' ## Fitting GridSearch')
  clf.fit(X_train, y_train)

  print("tuned hpyerparameters :(best parameters) ",clf.best_params_)
  print("score :",clf.best_score_)

In [ ]:
def scores(y_val, preds):
  print(' ## F1 Score (weighted) is -', f1_score(y_val, preds, average='weighted'))
  print(' ## Accuracy is -', accuracy_score(y_val, preds))
  print('      ')
  print('               Confusion Matrix')
  print(confusion_matrix(y_val, preds))

###**LR with FULL DATA**

#### With Averaged Vectors

In [ ]:
# BASELINE
run_model(lr, X_train_vec, y_train, X_val_vec, y_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5179993984471877
 ## Accuracy is - 0.517962710322874
      
               Confusion Matrix
[[558 522]
 [538 581]]


In [ ]:
run_model_gridsearch_lr(lr, X_train_vec, y_train, X_val_vec, y_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 3593.813663804626, 'penalty': 'l2'}
score : 0.515086937552015


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
# FINESUNED 
best_lr_full = LogisticRegression(penalty = 'l2', C = 3593.813663804626)
run_model(best_lr_full, X_train_vec, y_train, X_val_vec, y_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5197692060167853
 ## Accuracy is - 0.519781718963165
      
               Confusion Matrix
[[573 507]
 [549 570]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**PREDICTION ON TEST (w Avg Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_full_base = lr.predict(X_test_vec)
pred_lr_full_prob_base = lr.predict_proba(X_test_vec)
scores(y_test, pred_lr_full_base)

 ## F1 Score (weighted) is - 0.5173889777206634
 ## Accuracy is - 0.5173501577287066
      
               Confusion Matrix
[[1170 1089]
 [1053 1126]]


In [ ]:
#FINETUNED RESULT
pred_lr_full = best_lr_full.predict(X_test_vec)
pred_lr_full_prob = best_lr_full.predict_proba(X_test_vec)
scores(y_test, pred_lr_full)

 ## F1 Score (weighted) is - 0.5245992385409034
 ## Accuracy is - 0.5245606128886886
      
               Confusion Matrix
[[1184 1075]
 [1035 1144]]


In [ ]:
pred_lr_full_prob #[prob for class0, prob for class1]

array([[0.45513382, 0.54486618],
       [0.4308906 , 0.5691094 ],
       [0.37023349, 0.62976651],
       ...,
       [0.50978928, 0.49021072],
       [0.5311429 , 0.4688571 ],
       [0.40109193, 0.59890807]])

#### With Concantenated Vectors

In [ ]:
#BASELINE
run_model(lr, X_train_vec_concat, y_train, X_val_vec_concat, y_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5179993984471877
 ## Accuracy is - 0.517962710322874
      
               Confusion Matrix
[[558 522]
 [538 581]]


In [ ]:
run_model_gridsearch_lr(lr, X_train_vec_concat, y_train, X_val_vec_concat, y_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 2.7825594022071245, 'penalty': 'l2'}
score : 0.5128374049413716


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
#FINETUNED
best_lr_full_concat = LogisticRegression(penalty = 'l2', C = 2.7825594022071245)
run_model(best_lr_full_concat, X_train_vec_concat, y_train, X_val_vec_concat, y_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5178031935717086
 ## Accuracy is - 0.517962710322874
      
               Confusion Matrix
[[582 498]
 [562 557]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**PREDICTION ON TEST (w Concat Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_full_concat_base = lr.predict(X_test_vec_concat)
pred_lr_full_prob_concat_base = lr.predict_proba(X_test_vec_concat)
scores(y_test, pred_lr_full_concat_base)

 ## F1 Score (weighted) is - 0.5173889777206634
 ## Accuracy is - 0.5173501577287066
      
               Confusion Matrix
[[1170 1089]
 [1053 1126]]


In [ ]:
#FINETUNED RESULT
pred_lr_full_concat = best_lr_full_concat.predict(X_test_vec_concat)
pred_lr_full_prob_concat = best_lr_full_concat.predict_proba(X_test_vec_concat)
scores(y_test, pred_lr_full_concat)


 ## F1 Score (weighted) is - 0.5200812782739727
 ## Accuracy is - 0.5200540784136999
      
               Confusion Matrix
[[1185 1074]
 [1056 1123]]


In [ ]:
pred_lr_full_prob_concat #[prob for class0, prob for class1]

array([[0.43541843, 0.56458157],
       [0.4205097 , 0.5794903 ],
       [0.26461422, 0.73538578],
       ...,
       [0.46542256, 0.53457744],
       [0.51649599, 0.48350401],
       [0.43416939, 0.56583061]])

###**LR with SINGLE EMOJI**

#### With Averaged Vectors

In [ ]:
# FOR SINGLE EMOJI
run_model(lr, X_train_sing_vec, y_sing_train, X_val_sing_vec, y_sing_val)


     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5049510032156806
 ## Accuracy is - 0.5058058522991176
      
               Confusion Matrix
[[506 584]
 [480 583]]


In [ ]:
run_model_gridsearch_lr(lr, X_train_sing_vec, y_sing_train, X_val_sing_vec, y_sing_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 10000.0, 'penalty': 'l2'}
score : 0.5031135666609666


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
best_lr_sing = LogisticRegression(penalty = 'l2', C = 10000.0)
run_model(best_lr_sing, X_train_sing_vec, y_sing_train, X_val_sing_vec, y_sing_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5021978592440751
 ## Accuracy is - 0.5030190431955411
      
               Confusion Matrix
[[504 586]
 [484 579]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**PREDICTION ON TEST (w Avg Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_sing_base = lr.predict(X_test_sing_vec)
pred_lr_sing_prob_base = lr.predict_proba(X_test_sing_vec)
scores(y_sing_test, pred_lr_sing_base)

 ## F1 Score (weighted) is - 0.4869595082363849
 ## Accuracy is - 0.48721492743607464
      
               Confusion Matrix
[[1023 1181]
 [1045 1092]]


In [ ]:
#FINETUNED RESULT
pred_lr_sing = best_lr_sing.predict(X_test_sing_vec)
scores(y_sing_test, pred_lr_sing)

 ## F1 Score (weighted) is - 0.4878466603498624
 ## Accuracy is - 0.4879060124395301
      
               Confusion Matrix
[[1047 1157]
 [1066 1071]]


#### With Concatenated Vectors

In [ ]:
run_model(lr, X_train_sing_vec_concat, y_sing_train, X_val_sing_vec_concat, y_sing_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.4998031042482971
 ## Accuracy is - 0.5002322340919647
      
               Confusion Matrix
[[513 577]
 [499 564]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
run_model_gridsearch_lr(lr, X_train_sing_vec_concat, y_sing_train, X_val_sing_vec_concat, y_sing_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 21.544346900318832, 'penalty': 'l2'}
score : 0.5051196878848289


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
#FINETUNED 
best_lr_sing_concat = LogisticRegression(penalty = 'l2', C = 21.544346900318832)
run_model(best_lr_sing_concat, X_train_sing_vec_concat, y_sing_train, X_val_sing_vec_concat, y_sing_val)


     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.49451687383181664
 ## Accuracy is - 0.4946586158848119
      
               Confusion Matrix
[[520 570]
 [518 545]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**PREDICTION ON TEST (w Concat Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_sing_concat_base = lr.predict(X_test_sing_vec_concat)
pred_lr_sing_prob_concat_base = lr.predict_proba(X_test_sing_vec_concat)
scores(y_sing_test, pred_lr_sing_concat_base)

 ## F1 Score (weighted) is - 0.5002397398943275
 ## Accuracy is - 0.5003455425017277
      
               Confusion Matrix
[[1067 1137]
 [1032 1105]]


In [ ]:
#FINETUNED RESULT
pred_lr_sing_concat = best_lr_sing_concat.predict(X_test_sing_vec_concat)
scores(y_sing_test, pred_lr_sing_concat)

 ## F1 Score (weighted) is - 0.49732795452647843
 ## Accuracy is - 0.4973508408200875
      
               Confusion Matrix
[[1074 1130]
 [1052 1085]]


###**MULTI EMOJIS WITH REPEATS**

#### With Averaged Vectors

In [ ]:
# BASELINE
run_model(lr, X_train_mul_repeat_vec, y_mul_repeat_train, X_val_mul_repeat_vec, y_mul_repeat_val)


     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5187493899908503
 ## Accuracy is - 0.5189504373177842
      
               Confusion Matrix
[[651 556]
 [599 595]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
run_model_gridsearch_lr(lr, X_train_mul_repeat_vec, y_mul_repeat_train, X_val_mul_repeat_vec, y_mul_repeat_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 2.7825594022071245, 'penalty': 'l2'}
score : 0.5246267106645911


In [ ]:
#FINETUNED
best_lr_mul_repeat = LogisticRegression(penalty = 'l2', C = 2.7825594022071245)
run_model(best_lr_mul_repeat, X_train_mul_repeat_vec, y_mul_repeat_train, X_val_mul_repeat_vec, y_mul_repeat_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5062493741464569
 ## Accuracy is - 0.5064556434818825
      
               Confusion Matrix
[[636 571]
 [614 580]]


**PREDICTION ON TEST (w Avg Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_mul_base = lr.predict(X_test_mul_repeat_vec)
pred_lr_mul_prob_base = lr.predict_proba(X_test_mul_repeat_vec)
scores(y_mul_repeat_test, pred_lr_mul_base)

 ## F1 Score (weighted) is - 0.5220614269787021
 ## Accuracy is - 0.5220833333333333
      
               Confusion Matrix
[[1231 1159]
 [1135 1275]]


In [ ]:
#FINETUNED RESULT
pred_lr_mul_repeat = best_lr_mul_repeat.predict(X_test_mul_repeat_vec)
scores(y_mul_repeat_test, pred_lr_mul_repeat)

 ## F1 Score (weighted) is - 0.5193760638968085
 ## Accuracy is - 0.519375
      
               Confusion Matrix
[[1238 1152]
 [1155 1255]]


#### With Concantenated Vectors

In [ ]:
run_model(lr, X_train_mul_repeat_vec_concat, y_mul_repeat_train, X_val_mul_repeat_vec_concat, y_mul_repeat_val)


     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5187493899908503
 ## Accuracy is - 0.5189504373177842
      
               Confusion Matrix
[[651 556]
 [599 595]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
run_model_gridsearch_lr(lr, X_train_mul_repeat_vec_concat, y_mul_repeat_train, X_val_mul_repeat_vec_concat, y_mul_repeat_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 1.0, 'penalty': 'l2'}
score : 0.5222718993614576


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
best_lr_mul_repeat_concat = LogisticRegression(penalty = 'l2', C = 1.0)
run_model(best_lr_mul_repeat_concat, X_train_mul_repeat_vec_concat, y_mul_repeat_train, X_val_mul_repeat_vec_concat, y_mul_repeat_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5187493899908503
 ## Accuracy is - 0.5189504373177842
      
               Confusion Matrix
[[651 556]
 [599 595]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**PREDICTION ON TEST (w Concat Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_mul_concat_base = lr.predict(X_test_mul_repeat_vec_concat)
pred_lr_mul_prob_concat_base = lr.predict_proba(X_test_mul_repeat_vec_concat)
scores(y_mul_repeat_test, pred_lr_mul_concat_base)

 ## F1 Score (weighted) is - 0.5220614269787021
 ## Accuracy is - 0.5220833333333333
      
               Confusion Matrix
[[1231 1159]
 [1135 1275]]


In [ ]:
#FINETUNED RESULT
pred_lr_mul_repeat_concat = best_lr_mul_repeat_concat.predict(X_test_mul_repeat_vec_concat)
scores(y_mul_repeat_test, pred_lr_mul_repeat_concat)

 ## F1 Score (weighted) is - 0.5220614269787021
 ## Accuracy is - 0.5220833333333333
      
               Confusion Matrix
[[1231 1159]
 [1135 1275]]


###**FULL EMOJIS NO REPEATS**

#### With Averaged Vectors

In [ ]:
run_model(lr, X_train_mul_vec, y_mul_train, X_val_mul_vec, y_mul_val)


     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.519122216228706
 ## Accuracy is - 0.5190668461193361
      
               Confusion Matrix
[[572 514]
 [558 585]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
run_model_gridsearch_lr(lr, X_train_mul_vec, y_mul_train, X_val_mul_vec, y_mul_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 7.742636826811269, 'penalty': 'l2'}
score : 0.5058041572685422


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
best_lr_mul = LogisticRegression(penalty = 'l2', C = 7.742636826811269)
run_model(best_lr_mul, X_train_mul_vec, y_mul_train, X_val_mul_vec, y_mul_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.506974828951965
 ## Accuracy is - 0.5069537909376401
      
               Confusion Matrix
[[563 523]
 [576 567]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**PREDICTION ON TEST (w Avg Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_mul_base = lr.predict(X_test_mul_vec)
pred_lr_mul_prob__base = lr.predict_proba(X_test_mul_vec)
scores(y_mul_test, pred_lr_mul_base)

 ## F1 Score (weighted) is - 0.5158905918420099
 ## Accuracy is - 0.5159034513873224
      
               Confusion Matrix
[[1158 1064]
 [1082 1129]]


In [ ]:
#FINETUNED RESULT
pred_lr_mul = best_lr_mul.predict(X_test_mul_vec)
scores(y_mul_test, pred_lr_mul)

 ## F1 Score (weighted) is - 0.5097595798975241
 ## Accuracy is - 0.509812767877284
      
               Confusion Matrix
[[1156 1066]
 [1107 1104]]


#### With Concantenated Vectors

In [ ]:
run_model(lr, X_train_mul_vec_concat, y_mul_train, X_val_mul_vec_concat, y_mul_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.519122216228706
 ## Accuracy is - 0.5190668461193361
      
               Confusion Matrix
[[572 514]
 [558 585]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
run_model_gridsearch_lr(lr, X_train_mul_vec_concat, y_mul_train, X_val_mul_vec_concat, y_mul_val)

 ## Fitting GridSearch
tuned hpyerparameters :(best parameters)  {'C': 166.81005372000593, 'penalty': 'l2'}
score : 0.5102422337754854


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
best_lr_mul_concat = LogisticRegression(penalty = 'l2', C = 166.81005372000593)
run_model(best_lr_mul_concat, X_train_mul_vec_concat, y_mul_train, X_val_mul_vec_concat, y_mul_val)

     ## Fitting
     ## Predicting
 ## F1 Score (weighted) is - 0.5164243110024794
 ## Accuracy is - 0.5163750560789592
      
               Confusion Matrix
[[570 516]
 [562 581]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**PREDICTION ON TEST (w Concat Vectors)**

In [ ]:
#BASELINE RESULT
pred_lr_mul_concat_base = lr.predict(X_test_mul_vec_concat)
pred_lr_mul_prob_concat_base = lr.predict_proba(X_test_mul_vec_concat)
scores(y_mul_test, pred_lr_mul_concat_base)

 ## F1 Score (weighted) is - 0.5158905918420099
 ## Accuracy is - 0.5159034513873224
      
               Confusion Matrix
[[1158 1064]
 [1082 1129]]


In [ ]:
#FINETUNED RESULT
pred_lr_mul_concat = best_lr_mul_concat.predict(X_test_mul_vec_concat)
scores(y_mul_test, pred_lr_mul_concat)

 ## F1 Score (weighted) is - 0.5153876281750626
 ## Accuracy is - 0.515452289645838
      
               Confusion Matrix
[[1171 1051]
 [1097 1114]]


##**SUMMARY PREDICTION ON TEST**

###**w Avg Vectors**

In [ ]:
#FULL DATA
print("FULL DATA")
print("-------------------")
pred_lr_full = best_lr_full.predict(X_test_vec)
scores(y_test, pred_lr_full)
print("==========================================")

#FULL EMOJIS WITH NO REPEATS
print(" ")
print("FULL NO REPEATS")
print("-------------------")
pred_lr_mul = best_lr_mul.predict(X_test_mul_vec)
scores(y_mul_test, pred_lr_mul)
print("==========================================")

#SINGLE EMOJI
print(" ")
print("SINGLE EMOJI ONLY")
print("-------------------")
pred_lr_sing = best_lr_sing.predict(X_test_sing_vec)
scores(y_sing_test, pred_lr_sing)
print("==========================================")

#MULTI EMOJIS WITH REPEATS
print(" ")
print("MULTI EMOJIS ONLY WITH REPEATS")
print("-------------------")
pred_lr_mul_repeat = best_lr_mul_repeat.predict(X_test_mul_repeat_vec)
scores(y_mul_repeat_test, pred_lr_mul_repeat)




FULL DATA
-------------------
 ## F1 Score (weighted) is - 0.5245992385409034
 ## Accuracy is - 0.5245606128886886
      
               Confusion Matrix
[[1184 1075]
 [1035 1144]]
 
FULL NO REPEATS
-------------------
 ## F1 Score (weighted) is - 0.5097595798975241
 ## Accuracy is - 0.509812767877284
      
               Confusion Matrix
[[1156 1066]
 [1107 1104]]
 
SINGLE EMOJI ONLY
-------------------
 ## F1 Score (weighted) is - 0.4878466603498624
 ## Accuracy is - 0.4879060124395301
      
               Confusion Matrix
[[1047 1157]
 [1066 1071]]
 
MULTI EMOJIS ONLY WITH REPEATS
-------------------
 ## F1 Score (weighted) is - 0.5193760638968085
 ## Accuracy is - 0.519375
      
               Confusion Matrix
[[1238 1152]
 [1155 1255]]


###**w Concat Vectors**

In [ ]:
#FULL DATA
print("FULL DATA CONCAT")
print("-------------------")
pred_lr_full_concat = best_lr_full_concat.predict(X_test_vec_concat)
scores(y_test, pred_lr_full_concat)
print("==========================================")

#FULL EMOJIS WITH NO REPEATS
print(" ")
print("FULL NO REPEATS CONCAT")
print("-------------------")
# pred_lr_mul = best_lr_mul.predict(X_test_mul_vec)
# scores(y_mul_test, pred_lr_mul)
pred_lr_mul_concat = best_lr_mul_concat.predict(X_test_mul_vec_concat)
scores(y_mul_test, pred_lr_mul_concat)

print("==========================================")

#SINGLE EMOJI
print(" ")
print("SINGLE EMOJI ONLY CONCAT")
print("-------------------")
pred_lr_sing_concat = best_lr_sing_concat.predict(X_test_sing_vec_concat)
scores(y_sing_test, pred_lr_sing_concat)
print("==========================================")

#MULTI EMOJIS WITH REPEATS
print(" ")
print("MULTI EMOJIS ONLY WITH REPEATS CONCAT")
print("-------------------")
pred_lr_mul_repeat_concat = best_lr_mul_repeat_concat.predict(X_test_mul_repeat_vec_concat)
scores(y_mul_repeat_test, pred_lr_mul_repeat_concat)





FULL DATA CONCAT
-------------------
 ## F1 Score (weighted) is - 0.5200812782739727
 ## Accuracy is - 0.5200540784136999
      
               Confusion Matrix
[[1185 1074]
 [1056 1123]]
 
FULL NO REPEATS CONCAT
-------------------
 ## F1 Score (weighted) is - 0.5153876281750626
 ## Accuracy is - 0.515452289645838
      
               Confusion Matrix
[[1171 1051]
 [1097 1114]]
 
SINGLE EMOJI ONLY CONCAT
-------------------
 ## F1 Score (weighted) is - 0.49732795452647843
 ## Accuracy is - 0.4973508408200875
      
               Confusion Matrix
[[1074 1130]
 [1052 1085]]
 
MULTI EMOJIS ONLY WITH REPEATS CONCAT
-------------------
 ## F1 Score (weighted) is - 0.5220614269787021
 ## Accuracy is - 0.5220833333333333
      
               Confusion Matrix
[[1231 1159]
 [1135 1275]]
